title:       "Operating Systems 2021-2 (OS212)"
version:     "0021---25-Aug-2021"
copyright:   "2021-2021"
description: >- 
  This Is How Me Do It!
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-13"
author:           "Muhammad Haddad"
address:          "Depok"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://haddad9.github.io/os212/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/haddad9/os212/"
urlghpage:        "https://haddad9.github.io/os212/"
keywords:         "jekyll, testing"
github:           
  - metadata

